const MOVIES = {
	LOAD: 'LOAD',
	LOAD_SUCCESS: 'LOAD_SUCCESS',
	LOAD_FAIL: 'LOAD_FAIL',

	LOAD_DETAIL: 'LOAD_DETAIL',
	LOAD_DETAIL_SUCCESS: 'LOAD_DETAIL_SUCCESS',
	LOAD_DETAIL_FAIL: 'LOAD_DETAIL_FAIL',
	REMOVE_DETAIL: 'REMOVE_DETAIL',

	ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
	REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES',
}

const PAGE = {
	RESET_PAGING: 'RESET_PAGING',
	EXACT_PAGE: 'EXACT_PAGE',
}

const RESET = 'RESET_APPLICATION_STATE'

export { MOVIES, PAGE, RESET }
